version: 2

_environemnt:
  WORKSPACE_PATH: &WORKSPACE_PATH /tmp/workspace
  PROJECT_PATH_DEFAULT: &PROJECT_PATH_DEFAULT /root/project
  PROJECT_PATH_CIRCLECI: &PROJECT_PATH_CIRCLECI /home/circleci/project
  environment_default: &environment_default
    WORKSPACE_PATH: *WORKSPACE_PATH
    PROJECT_PATH: *PROJECT_PATH_DEFAULT
  environment_circleci: &environment_circleci
    WORKSPACE_PATH: *WORKSPACE_PATH
    PROJECT_PATH: *PROJECT_PATH_CIRCLECI

_conditions:
  cond_on_branch: &cond_on_branch
    # default condition is on any branch and no tags
    {}
  cond_master: &cond_master
    filters:
      branches:
        only: master

_steps:
  # common setup
  make_dirs: &make_dirs
    run:
      name: Make directories
      command: mkdir $WORKSPACE_PATH
  # npm
  update_npm: &update_npm
    run:
      name: Update npm
      command: npm install npm@6.9.0 -g
  install_npm_packages: &install_npm_packages
    run:
      name: Install npm packages
      command: npm ci
  # workspace
  copy_dist_to_workspace: &copy_dist_to_workspace
    run:
      name: Copy dist into workspace
      command: cp -r $PROJECT_PATH/dist/ $WORKSPACE_PATH/dist/
  persist_workspace: &persist_workspace
    persist_to_workspace:
      root: *WORKSPACE_PATH
      paths:
        - dist
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *WORKSPACE_PATH
  extract_dist_from_workspace: &extract_dist_from_workspace
    run:
      name: Extract dist from workspace
      command: cp -r $WORKSPACE_PATH/dist/ $PROJECT_PATH/dist/

jobs:
  build:
    docker:
      - image: node:8.11.4
    environment:
      <<: *environment_default
    steps:
      - checkout
      - *make_dirs
      - *update_npm
      - *install_npm_packages
      - run:
          name: Build application
          command: npm run build
      - *copy_dist_to_workspace
      - *persist_workspace
  build_chroma:
    docker:
      - image: node:8.11.4
    environment:
      <<: *environment_default
    steps:
      - checkout
      - *make_dirs
      - *update_npm
      - *install_npm_packages
      - run:
          name: Build application
          command: npm run buildChroma
      - *copy_dist_to_workspace
      - *persist_workspace
  test:
    docker:
      - image: node:8.11.4
    environment:
      <<: *environment_default
    steps:
      - checkout
      - *update_npm
      - *install_npm_packages
      - run:
          name: Unit tests
          command: npm run test
  upload:
    docker:
      - image: circleci/python:3.7.2
    environment:
      <<: *environment_circleci
    steps:
      - *make_dirs
      - *attach_workspace
      - *extract_dist_from_workspace
      - run:
          name: Install aws cli
          command: |
            pip3 install awscli==1.16.127 --user
      - run:
          name: Sync webserver
          command: ~/.local/bin/aws s3 sync dist/ s3://wes-develop.com/ --delete
      - run:
          name: Invalidate CDN cahced entrypoints
          command: |
            ~/.local/bin/aws cloudfront create-invalidation \
              --distribution-id E1N4FFELPXS3GO \
              --paths /index.html
  upload_chroma:
    docker:
      - image: circleci/python:3.7.2
    environment:
      <<: *environment_circleci
    steps:
      - *make_dirs
      - *attach_workspace
      - *extract_dist_from_workspace
      - run:
          name: Install aws cli
          command: |
            pip3 install awscli==1.16.127 --user
      - run:
          name: Sync webserver
          command: ~/.local/bin/aws s3 sync dist/ s3://chroma-app/ --delete

workflows:
  version: 2
  on_push:
    jobs:
      - test:
          <<: *cond_on_branch
      - build:
          <<: *cond_on_branch
      - upload:
          <<: *cond_master
          requires:
            - build
            - test
      - build_chroma:
          <<: *cond_on_branch
      - upload_chroma:
          <<: *cond_master
          requires:
            - build_chroma
            - test
